apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-server
  labels:
    app: auth-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api-server
  template:
    metadata:
      labels:
        app: auth-api-server
    spec:
      imagePullSecrets:
        - name: facegram-registery
      containers:
        - name: auth-api-server
          image: cr.fcgm.dev/facegram/auth-service:226d6e7c
          ports:
            - containerPort: 8080
            - containerPort: 30004
            - containerPort: 30005
            - containerPort: 30006
            - containerPort: 30007
          env:
            - name: NODE_ENV
              value: "dev"   
          envFrom:
            - secretRef:
                name: grpc-client-configs
            - secretRef:
                name: grpc-client-urls 
            - secretRef:
                name: sentry-credential
            - secretRef:
                name: mongodb-credential  
            - secretRef:
                name: redis-credential
            - secretRef:
                name: rabbitmq-credential
            - secretRef:
                name: aes-keys                                                  
